<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4019.2">
  <POU Name="MAIN" Id="{5aa039c4-acf9-4778-abe4-2f2bcc02fb57}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	_REQUEST : C_HTTP_REQUEST;
	_STRING : STRING(255);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_STRING := _REQUEST.ToString();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>