<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4019.2">
  <POU Name="C_RESTFUL_SERVER" Id="{2ed9c24a-91ed-4ae7-bf9b-56c52a3bf700}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK C_RESTFUL_SERVER
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>